### limiter
## From searxng/searxng-docker setup --> https://github.com/searxng/searxng-docker
## Original file --> https://github.com/searxng/searxng-docker/blob/master/searxng/limiter.toml

# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection.ip_limit]
# activate advanced bot protection
# enable this when running the instance for a public usage on the internet
link_token = false


## Lauren Street 2025/09/12:
## Modifications compared to the original: https://github.com/searxng/searxng-docker/blob/master/searxng/limiter.toml
# 1. Just added more comments for attribution